version: 2.1

executors:
  exeggutor:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/pyls
    environment:
      PYTHON_VERSION: "3.6"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      DROPBOX_URL: "https://www.dropbox.com/s/e6jfvekw6habeud/matlab_pls.tar.gz?dl=1"

jobs:
  setup:
    executor: exeggutor
    steps:
      - checkout
      - run:
          name: Generating checksum to cache Matlab PLS results
          command: echo "${DROPBOX_URL}" > checksum.txt
      - restore_cache:
          name: Checking for cached Matlab PLS results
          keys:
            - data-v2-{{ checksum "checksum.txt" }}
            - data-v2-
      - run:
          name: Preparing Matlab PLS results
          command: |
            if [[ -e /tmp/data/matlab ]]; then
              echo "Restoring Matlab PLS results from cache"
            else
                mkdir -p /tmp/data/matlab
                curl -L "${DROPBOX_URL}" | tar xz -C /tmp/data/matlab
            fi
      - save_cache:
          name: Caching Matlab PLS results
          key: data-v2-{{ checksum "checksum.txt" }}
          paths:
            - /tmp/data
      - restore_cache:
          name: Restoring cached dependencies
          keys:
            - dependencies-v3-{{ checksum "requirements.txt" }}
            - dependencies-v3-
      - run:
          name: Creating test environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[tests]
            pip install joblib
      - save_cache:
          name: Caching dependencies
          key: dependencies-v3-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - persist_to_workspace:
          name: Persisting workspace
          root: ./
          paths:
            - requirements.txt
            - checksum.txt


  behavioral_pls:
    executor: exeggutor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Loading Matlab PLS results
          keys:
            - data-v2-{{ checksum "checksum.txt" }}
            - data-v2-
      - restore_cache:
          name: Loading dependencies
          keys:
          - dependencies-v3-{{ checksum "requirements.txt" }}
          - dependencies-v3-
      - run:
          name: Running Matlab-Python comparison
          command: |
            . venv/bin/activate
            for mat in /tmp/data/matlab/bpls*mat; do
              echo $( date +%H:%M:%S ) "${mat}"
              python -c "import pyls.tests; pyls.tests.assert_matlab_equivalence('${mat}', n_proc='max', n_perm=2500, n_split=100);"
            done

  meancentered_pls:
    executor: exeggutor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Loading Matlab PLS results
          keys:
            - data-v2-{{ checksum "checksum.txt" }}
            - data-v2-
      - restore_cache:
          name: Loading dependencies
          keys:
          - dependencies-v3-{{ checksum "requirements.txt" }}
          - dependencies-v3-
      - run:
          name: Running Matlab-Python comparison
          command: |
            . venv/bin/activate
            for mat in /tmp/data/matlab/mpls*mat; do
              echo $( date +%H:%M:%S ) "${mat}"
              python -c "import pyls.tests; pyls.tests.assert_matlab_equivalence('${mat}', n_proc='max', n_perm=2500, n_split=250);"
            done

workflows:
  version: 2.1
  regression_tests:
    jobs:
      - setup
      - behavioral_pls:
          requires:
            - setup
      - meancentered_pls:
          requires:
            - setup
